"""Ticket backend abstraction — pluggable backends for ticket/PR operations.

Supports:
  - local: Markdown files in .ops/tickets/ (default, no external deps)
  - jira: Atlassian Jira REST API

Switch via config: AGENT_TICKET_BACKEND=local|jira
"""

from __future__ import annotations

import logging
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


@dataclass
class Ticket:
    """Normalized ticket representation across all backends."""

    id: str
    title: str
    description: str
    severity: str = "medium"
    category: str = "incident"
    status: str = "Open"
    assignee: str | None = None
    related_files: str | None = None
    url: str | None = None  # Jira URL, or local file path
    created_at: str | None = None


class TicketBackend(ABC):
    """Abstract interface for ticket operations."""

    @abstractmethod
    def create(
        self,
        title: str,
        description: str,
        severity: str = "medium",
        category: str = "incident",
        assignee: str | None = None,
        related_files: str | None = None,
    ) -> Ticket:
        """Create a ticket. Returns the created ticket with ID and URL."""

    @abstractmethod
    def list_tickets(self, status: str | None = None) -> list[Ticket]:
        """List tickets, optionally filtered by status."""

    @abstractmethod
    def update(
        self,
        ticket_id: str,
        status: str | None = None,
        resolution: str | None = None,
    ) -> Ticket | None:
        """Update a ticket. Returns updated ticket, or None if not found."""

    @abstractmethod
    def get(self, ticket_id: str) -> Ticket | None:
        """Get a single ticket by ID."""


# ── Local Backend ─────────────────────────────────────────────


class LocalTicketBackend(TicketBackend):
    """Stores tickets as markdown files in <workspace>/.ops/tickets/."""

    def __init__(self, workspace_root: str):
        self.workspace_root = workspace_root

    @property
    def _ticket_dir(self) -> str:
        d = os.path.join(self.workspace_root, ".ops", "tickets")
        os.makedirs(d, exist_ok=True)
        return d

    def create(
        self,
        title: str,
        description: str,
        severity: str = "medium",
        category: str = "incident",
        assignee: str | None = None,
        related_files: str | None = None,
    ) -> Ticket:
        now = datetime.now(timezone.utc)
        date_str = now.strftime("%Y%m%d")
        prefix = "INC" if category == "incident" else "TASK"

        existing = [
            f for f in os.listdir(self._ticket_dir)
            if f.startswith(f"{prefix}-{date_str}-")
        ]
        seq = len(existing) + 1
        ticket_id = f"{prefix}-{date_str}-{seq:03d}"

        assignee_line = f"**Assignee:** {assignee}" if assignee else "**Assignee:** Unassigned"
        files_section = f"\n## Related Files\n\n{related_files}\n" if related_files else ""

        content = f"""# {ticket_id}: {title}

**Severity:** {severity}
**Category:** {category}
**Status:** Open
{assignee_line}
**Created:** {now.strftime("%Y-%m-%d %H:%M UTC")}

## Description

{description}
{files_section}
## Resolution

_Pending_

---
*Generated by MCP Agent*
"""
        path = os.path.join(self._ticket_dir, f"{ticket_id}.md")
        with open(path, "w") as f:
            f.write(content)

        return Ticket(
            id=ticket_id,
            title=title,
            description=description,
            severity=severity,
            category=category,
            status="Open",
            assignee=assignee,
            related_files=related_files,
            url=f".ops/tickets/{ticket_id}.md",
            created_at=now.strftime("%Y-%m-%d %H:%M UTC"),
        )

    def list_tickets(self, status: str | None = None) -> list[Ticket]:
        if not os.path.isdir(self._ticket_dir):
            return []

        tickets = []
        for fname in sorted(os.listdir(self._ticket_dir)):
            if not fname.endswith(".md"):
                continue
            ticket = self._parse_ticket_file(fname)
            if ticket and (not status or ticket.status.lower() == status.lower()):
                tickets.append(ticket)
        return tickets

    def update(
        self,
        ticket_id: str,
        status: str | None = None,
        resolution: str | None = None,
    ) -> Ticket | None:
        path = os.path.join(self._ticket_dir, f"{ticket_id}.md")
        if not os.path.isfile(path):
            return None

        with open(path, "r") as f:
            content = f.read()

        if status:
            # Replace any status
            import re
            content = re.sub(r"\*\*Status:\*\* \w+", f"**Status:** {status}", content)

        if resolution:
            content = content.replace("_Pending_", resolution)

        with open(path, "w") as f:
            f.write(content)

        return self._parse_ticket_file(f"{ticket_id}.md")

    def get(self, ticket_id: str) -> Ticket | None:
        return self._parse_ticket_file(f"{ticket_id}.md")

    def _parse_ticket_file(self, fname: str) -> Ticket | None:
        path = os.path.join(self._ticket_dir, fname)
        if not os.path.isfile(path):
            return None
        with open(path, "r") as f:
            content = f.read()

        ticket_id = fname.replace(".md", "")
        title = ticket_id
        status = "Unknown"
        severity = "medium"
        category = "incident"

        for line in content.split("\n"):
            if line.startswith("# "):
                title = line[2:].strip()
            elif line.startswith("**Status:**"):
                status = line.split("**Status:**")[1].strip()
            elif line.startswith("**Severity:**"):
                severity = line.split("**Severity:**")[1].strip()
            elif line.startswith("**Category:**"):
                category = line.split("**Category:**")[1].strip()

        return Ticket(
            id=ticket_id,
            title=title,
            description="",
            severity=severity,
            category=category,
            status=status,
            url=f".ops/tickets/{fname}",
        )


# ── Jira Backend ──────────────────────────────────────────────


@dataclass
class JiraConfig:
    """Jira connection settings — all from environment/config."""

    base_url: str  # e.g., https://company.atlassian.net
    email: str
    api_token: str
    project_key: str  # e.g., OPS
    default_issue_type: str = "Bug"
    severity_field: str = "priority"  # Jira field name for severity
    # Mapping: our severity → Jira priority name
    severity_map: dict[str, str] | None = None

    def __post_init__(self):
        if self.severity_map is None:
            self.severity_map = {
                "critical": "Highest",
                "high": "High",
                "medium": "Medium",
                "low": "Low",
            }


class JiraTicketBackend(TicketBackend):
    """Jira REST API v3 backend.

    Requires: pip install requests (already in most environments).
    Config via env vars: AGENT_JIRA_URL, AGENT_JIRA_EMAIL, AGENT_JIRA_TOKEN, AGENT_JIRA_PROJECT
    """

    def __init__(self, config: JiraConfig):
        self.config = config
        self._session = None

    @property
    def session(self):
        if self._session is None:
            import requests
            self._session = requests.Session()
            self._session.auth = (self.config.email, self.config.api_token)
            self._session.headers.update({
                "Content-Type": "application/json",
                "Accept": "application/json",
            })
        return self._session

    def _api(self, path: str) -> str:
        return f"{self.config.base_url.rstrip('/')}/rest/api/3{path}"

    def create(
        self,
        title: str,
        description: str,
        severity: str = "medium",
        category: str = "incident",
        assignee: str | None = None,
        related_files: str | None = None,
    ) -> Ticket:
        priority_name = self.config.severity_map.get(severity, "Medium")

        # Jira ADF (Atlassian Document Format) for description
        desc_content = description
        if related_files:
            desc_content += f"\n\nRelated files:\n{related_files}"

        payload = {
            "fields": {
                "project": {"key": self.config.project_key},
                "summary": title,
                "description": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                        {
                            "type": "paragraph",
                            "content": [{"type": "text", "text": desc_content}],
                        }
                    ],
                },
                "issuetype": {"name": self.config.default_issue_type},
                "priority": {"name": priority_name},
                "labels": [category],
            }
        }

        resp = self.session.post(self._api("/issue"), json=payload)
        resp.raise_for_status()
        data = resp.json()
        ticket_id = data["key"]
        url = f"{self.config.base_url}/browse/{ticket_id}"

        return Ticket(
            id=ticket_id,
            title=title,
            description=description,
            severity=severity,
            category=category,
            status="Open",
            assignee=assignee,
            url=url,
        )

    def list_tickets(self, status: str | None = None) -> list[Ticket]:
        jql = f"project = {self.config.project_key} ORDER BY created DESC"
        if status:
            jql = f"project = {self.config.project_key} AND status = '{status}' ORDER BY created DESC"

        resp = self.session.get(
            self._api("/search"),
            params={"jql": jql, "maxResults": 50, "fields": "summary,status,priority,labels"},
        )
        resp.raise_for_status()
        data = resp.json()

        tickets = []
        for issue in data.get("issues", []):
            fields = issue["fields"]
            tickets.append(Ticket(
                id=issue["key"],
                title=fields.get("summary", ""),
                description="",
                severity=fields.get("priority", {}).get("name", "Medium"),
                status=fields.get("status", {}).get("name", "Unknown"),
                url=f"{self.config.base_url}/browse/{issue['key']}",
            ))
        return tickets

    def update(
        self,
        ticket_id: str,
        status: str | None = None,
        resolution: str | None = None,
    ) -> Ticket | None:
        if resolution:
            # Add comment with resolution
            comment_payload = {
                "body": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                        {
                            "type": "paragraph",
                            "content": [
                                {"type": "text", "text": f"Resolution: {resolution}"}
                            ],
                        }
                    ],
                }
            }
            resp = self.session.post(
                self._api(f"/issue/{ticket_id}/comment"), json=comment_payload
            )
            resp.raise_for_status()

        if status:
            # Get available transitions
            resp = self.session.get(self._api(f"/issue/{ticket_id}/transitions"))
            resp.raise_for_status()
            transitions = resp.json().get("transitions", [])

            target = next(
                (t for t in transitions if t["name"].lower() == status.lower()),
                None,
            )
            if target:
                self.session.post(
                    self._api(f"/issue/{ticket_id}/transitions"),
                    json={"transition": {"id": target["id"]}},
                )

        return self.get(ticket_id)

    def get(self, ticket_id: str) -> Ticket | None:
        resp = self.session.get(
            self._api(f"/issue/{ticket_id}"),
            params={"fields": "summary,status,priority,labels"},
        )
        if resp.status_code == 404:
            return None
        resp.raise_for_status()
        data = resp.json()
        fields = data["fields"]
        return Ticket(
            id=data["key"],
            title=fields.get("summary", ""),
            description="",
            severity=fields.get("priority", {}).get("name", "Medium"),
            status=fields.get("status", {}).get("name", "Unknown"),
            url=f"{self.config.base_url}/browse/{data['key']}",
        )


# ── Factory ───────────────────────────────────────────────────


def create_ticket_backend(backend_type: str = "local", **kwargs) -> TicketBackend:
    """Factory: create ticket backend based on config.

    Args:
        backend_type: "local" or "jira"
        **kwargs: backend-specific config overrides

    For Jira, reads from env vars if not provided in kwargs:
        AGENT_JIRA_URL, AGENT_JIRA_EMAIL, AGENT_JIRA_TOKEN, AGENT_JIRA_PROJECT
    """
    if backend_type == "jira":
        config = JiraConfig(
            base_url=kwargs.get("jira_url") or os.environ["AGENT_JIRA_URL"],
            email=kwargs.get("jira_email") or os.environ["AGENT_JIRA_EMAIL"],
            api_token=kwargs.get("jira_token") or os.environ["AGENT_JIRA_TOKEN"],
            project_key=kwargs.get("jira_project") or os.environ.get("AGENT_JIRA_PROJECT", "OPS"),
            default_issue_type=kwargs.get("jira_issue_type", "Bug"),
        )
        logger.info("✅ Using Jira ticket backend: %s project=%s", config.base_url, config.project_key)
        return JiraTicketBackend(config)

    if backend_type == "local":
        from app.tools.agent_mode import get_workspace_root
        workspace = kwargs.get("workspace_root") or get_workspace_root()
        logger.info("✅ Using local ticket backend: %s", workspace)
        return LocalTicketBackend(workspace)

    raise ValueError(f"Unknown ticket backend: {backend_type}. Supported: local, jira")
